### ISSUE TITLE
Blocks with 'name' argument is limited to 64 characters

### ISSUE THREAD

**Issue by shanecottey** [fortinetdev/terraform-provider-fortios#177]
When attempting to build a [fortios_firewall_vipgrp](https://registry.terraform.io/providers/fortinetdev/fortios/latest/docs/resources/fortios_firewall_vipgrp) that contains dozens of [fortios_firewall_vip](https://registry.terraform.io/providers/fortinetdev/fortios/latest/docs/resources/fortios_firewall_vip) objects as members, I am receiving an error that says
`Error: expected length of member.name to be in the range (0 - 64), got <vip1> <vip2> <vip3> etc...`

This is a major hindrance to what we are trying to accomplish, and it seems odd to me that through the CLI and WebUI I have no issues adding tons of VIPs of varying character lengths into one VIP Group.
I thought maybe I could get around this by skipping a VIP Group, and just adding all of the individual VIPs into a [fortios_firewall_policy](https://registry.terraform.io/providers/fortinetdev/fortios/latest/docs/resources/fortios_firewall_policy) object, but I receive a similar error complaining about character limit 0-64 on the **dstaddr{}** block.

When I shrink the number of VIPs I'm trying to associate with a VIP Group/Policy in Terraform so that the character count is under 64, it works fine...  But this defeats the purpose of what I am trying to accomplish with the FortiOS Terraform provider.

Is there a reason this is so limited?
We spin up servers that each require 12 unique VIP objects for allowing inbound access on various ports.  I am able to do this with the CLI and appending members to a VIP Group, so why the major difference when leveraging Terraform?

**Environment Info:**
Terraform version ==> 1.0.6 (windows_amd64)
FortiOS provider version ==> 1.13.1
Fortigate FW firmware ==> 6.2.9 build1234(GA)

**Comment by lix-fortinet** [comment]
Hi @shanecottey ,

Thank you for raising this issue. This is a problem caused by schema merging. FOS v6.0 has the length limitation of 63 characters. But after v6.2, it has extended to 79 characters.

Team are working on this issue. And we will fix it in the next release. Before that, you could use generic resource as alternatives:
`https://registry.terraform.io/providers/fortinetdev/fortios/latest/docs/resources/fortios_json_generic_api`

Please let me know if you have any questions.

Thanks,
Xing

**Comment by lix-fortinet** [comment]
Hi @shanecottey ,

This issue has been fixed in the latest release of v1.13.2. 

Please let me know if you have any questions.

Thanks,
Xing

**Comment by shanecottey** [comment]
Xing,

Thanks for the feedback, however, this is still not suitable for our needs.
We are trying to create a VIP group that has 12 different VIPs in it, and each VIP name is ~20 characters long.
Even trying to do this with the generic JSON API wrapper, we run into issues.  Why is the character limitation so small for the **member{}** block?

In the CLI this does not seem to be an issue--
`
conf fire vipgrp
edit <vipgrp name>
set member <vip1> <vip2> <vip3> etc...
`

-Shane

**Comment by lix-fortinet** [comment]
Hi @shanecottey ,

I got what you mean. The way to add multiple block items is to add blocks with different content. Like this:
```
resource "fortios_firewall_vipgrp" "trname" {
  color     = 0
  interface = "any"
  name      = "vipgrp1"

  member {
    name = <vip1>
  }

  member {
    name = <vip2>
  }
}
```

Please let me know if this could solve your problem.

Thanks,
Xing

**Comment by shanecottey** [comment]
Xing,

This is exactly what I was looking for!  Thanks for the clarification!

-Shane

**Comment by lix-fortinet** [comment]
Hi @shanecottey ,

You are very welcome! If you do not have further questions, I will close this issue. 

Feel free to open issues if you have any questions.

Thanks,
Xing
