### ISSUE TITLE
Provider always re-submits DHCP reserved addresses

### ISSUE THREAD

**Issue by rf152** [fortinetdev/terraform-provider-fortios#355]
I have a `fortios_systemdhcp_server` resource with a number of reserved addresses (dynamically pulled in from yaml).

Each time I run a terraform apply, it wants to re-create the reserved addresses.

The reserved addresses block is as such:
```
  dynamic reserved_address {
    for_each    = { for reservation in try(each.value.reservations, []) : reservation.mac => reservation }
    content {
      id        = index(each.value.reservations, reserved_address.value) + 1
      type      = "mac"
      mac       = reserved_address.value.mac
      ip        = reserved_address.value.ip
      action    = "reserved"
      description = reserved_address.value.description
    }
  }
```

and when I run a terraform apply, it wants to edit it like so:

```
~ resource "fortios_systemdhcp_server" "dhcp" {
        id                           = "2"
        # (48 unchanged attributes hidden)

      ~ reserved_address {
          ~ description     = "host-a" -> "host-b"
          ~ id              = 3 -> 4
          ~ ip              = "10.0.0.128" -> "10.0.0.194"
          ~ mac             = "00:a0:98:11:14:f1" -> "00:02:c9:54:e1:30"
            # (6 unchanged attributes hidden)
        }
      ~ reserved_address {
          ~ description     = "host-c" -> "host-a"
          ~ id              = 1 -> 3
          ~ ip              = "10.0.0.10" -> "10.0.0.128"
          ~ mac             = "8c:85:90:32:c9:28" -> "00:a0:98:11:14:f1"
            # (6 unchanged attributes hidden)
        }
      ~ reserved_address {
          ~ description     = "host-d" -> "host-c"
          ~ id              = 2 -> 1
          ~ ip              = "10.0.0.91" -> "10.0.0.10"
          ~ mac             = "92:91:ab:3c:26:53" -> "8c:85:90:32:c9:28"
            # (6 unchanged attributes hidden)
        }
      ~ reserved_address {
          ~ description     = "host-b" -> "host-d"
          ~ id              = 4 -> 2
          ~ ip              = "10.0.0.194" -> "10.0.0.91"
          ~ mac             = "00:02:c9:54:e1:30" -> "92:91:ab:3c:26:53"
            # (6 unchanged attributes hidden)
        }

        # (1 unchanged block hidden)
    }
```

I would expect the provider to be able to realise that the reserved addresses are the same in the terraform definition as applied to the device itself, and it appears to just be changing the order in which they are applied in the config.

**Comment by MaxxLiu22** [comment]
Hi @rf152 ,

I was able to reproduce the problem, and the reason is that FOS retains the order of reserved_address objects when creating them, and it cannot be updated. Meanwhile, Terraform strictly compares this order with your Terraform files.

As a workaround, you may manually adjust the order of your reserved_address objects in your Terraform configuration to match the existing order, or delete and recreate them based on your desired order.

I have reported this issue to the development team to explore possible improvements. Thank you for your patience!

Thanks,
Maxx

**Comment by rf152** [comment]
Thanks Maxx,

The config is in a for_each loop, and the order has not changed at all. Ideally, the provider would sort (using whatever algorithm the FortiGate uses to sort) before comparing the configuration, as that would then resolve the issue.

I'll keep an eye on this issue to see what the development team come back with.

Thanks
rf152

**Comment by ebarrett-Ocient** [comment]
Unfortunately, the workaround didn't work for me, either. My reserved addresses are in the same order in terraform code as they are in my Fortigate's configuration.

**Comment by waza-ari** [comment]
That issue also happens for instances with only a single reserved address, so order doesn't seem to be an issue.

**Comment by MaxxLiu22** [comment]
Hi all,

This issue should have been addressed in version 1.22.1. Please feel free to give it a try at your convenience.

For context, Terraform will acquire the actual order of blocks and store it in the state file.

If ``dynamic_sort_subtable = true``, Terraform will sort the state file blocks before comparing them with the configuration in the .tf files.

If ``dynamic_sort_subtable = false`` (or not set), Terraform will directly compare the real block order with the configuration in the .tf files.

**Comment by waza-ari** [comment]
We're still seeing that issue I'm afraid. It doesn't matter how `dynamic_sort_subtable` is set, when creating a resource (e.g. `fortios_systemdhcp_server.vlan80_dhcp`) everything works, when then running apply again, it wants to change the order. Changing the order then also fails due to duplicate entries:

```
terraform-fortinet git:(master) ✗ terraform apply --target fortios_systemdhcp_server.vlan80_dhcp
fortios_system_interface.mksp_inside: Refreshing state... [id=port1]
fortios_system_interface.vlan_interfaces["VLAN_20"]: Refreshing state... [id=VLAN_20]
fortios_system_interface.vlan_interfaces["VLAN_110"]: Refreshing state... [id=VLAN_110]
fortios_system_interface.vlan_interfaces["VLAN_90"]: Refreshing state... [id=VLAN_90]
fortios_system_interface.vlan_interfaces["VLAN_80"]: Refreshing state... [id=VLAN_80]
fortios_system_interface.vlan_interfaces["VLAN_30"]: Refreshing state... [id=VLAN_30]
fortios_system_interface.vlan_interfaces["VLAN_1100"]: Refreshing state... [id=VLAN_1100]
fortios_system_interface.vlan_interfaces["VLAN_60"]: Refreshing state... [id=VLAN_60]
fortios_system_interface.vlan_interfaces["VLAN_10"]: Refreshing state... [id=VLAN_10]
fortios_system_interface.vlan_interfaces["VLAN_40"]: Refreshing state... [id=VLAN_40]
fortios_system_interface.vlan_interfaces["VLAN_50"]: Refreshing state... [id=VLAN_50]
fortios_system_interface.vlan_interfaces["VLAN_70"]: Refreshing state... [id=VLAN_70]
fortios_systemdhcp_server.vlan80_dhcp: Refreshing state... [id=80]

Terraform used the selected providers to generate the following execution plan. Resource actions are
indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  # fortios_systemdhcp_server.vlan80_dhcp will be updated in-place
  ~ resource "fortios_systemdhcp_server" "vlan80_dhcp" {
        id                           = "80"
        # (47 unchanged attributes hidden)

      ~ reserved_address {
          ~ description     = "Talos DB Node 1" -> "Talos Worker Node 1"
            id              = 4
          ~ ip              = "10.1.80.31" -> "10.1.80.21"
          ~ mac             = "bc:24:11:af:58:05" -> "bc:24:11:6d:de:0a"
            # (6 unchanged attributes hidden)
        }
      ~ reserved_address {
          ~ description     = "Talos MGMT Node 1" -> "Talos Worker Node 2"
            id              = 5
          ~ ip              = "10.1.80.11" -> "10.1.80.22"
          ~ mac             = "bc:24:11:6d:ca:32" -> "bc:24:11:c1:0e:4f"
            # (6 unchanged attributes hidden)
        }
      ~ reserved_address {
          ~ description     = "Talos MGMT Node 2" -> "Talos Worker Node 3"
            id              = 6
          ~ ip              = "10.1.80.12" -> "10.1.80.23"
          ~ mac             = "bc:24:11:dd:fc:9e" -> "bc:24:11:4c:03:75"
            # (6 unchanged attributes hidden)
        }
      ~ reserved_address {
          ~ description     = "Talos MGMT Node 3" -> "Talos DB Node 1"
            id              = 7
          ~ ip              = "10.1.80.13" -> "10.1.80.31"
          ~ mac             = "bc:24:11:5f:92:d1" -> "bc:24:11:af:58:05"
            # (6 unchanged attributes hidden)
        }
      ~ reserved_address {
          ~ description     = "Talos DB Node 2" -> "Talos MGMT Node 1"
            id              = 8
          ~ ip              = "10.1.80.32" -> "10.1.80.11"
          ~ mac             = "bc:24:11:85:c0:42" -> "bc:24:11:6d:ca:32"
            # (6 unchanged attributes hidden)
        }
      ~ reserved_address {
          ~ description     = "Talos Worker Node 1" -> "Talos MGMT Node 2"
            id              = 1
          ~ ip              = "10.1.80.21" -> "10.1.80.12"
          ~ mac             = "bc:24:11:6d:de:0a" -> "bc:24:11:dd:fc:9e"
            # (6 unchanged attributes hidden)
        }
      ~ reserved_address {
          ~ description     = "Talos Worker Node 2" -> "Talos MGMT Node 3"
            id              = 2
          ~ ip              = "10.1.80.22" -> "10.1.80.13"
          ~ mac             = "bc:24:11:c1:0e:4f" -> "bc:24:11:5f:92:d1"
            # (6 unchanged attributes hidden)
        }
      ~ reserved_address {
          ~ description     = "Talos Worker Node 3" -> "Talos DB Node 2"
            id              = 3
          ~ ip              = "10.1.80.23" -> "10.1.80.32"
          ~ mac             = "bc:24:11:4c:03:75" -> "bc:24:11:85:c0:42"
            # (6 unchanged attributes hidden)
        }

        # (1 unchanged block hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.
╷
│ Warning: Resource targeting is in effect
│ 
│ You are creating a plan with the -target option, which means that the result of this plan may not represent
│ all of the changes requested by the current configuration.
│ 
│ The -target option is not for routine use, and is provided only for exceptional situations such as
│ recovering from errors or mistakes, or when Terraform specifically suggests to use it as part of an error
│ message.
╵

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

fortios_systemdhcp_server.vlan80_dhcp: Modifying... [id=80]
╷
│ Warning: Applied changes may be incomplete
│ 
│ The plan was created with the -target option in effect, so some changes requested in the configuration may
│ have been ignored and the output values may not be fully updated. Run the following command to verify that
│ no other changes are pending:
│     terraform plan
│ 
│ Note that the -target option is not suitable for routine use, and is provided only for exceptional
│ situations such as recovering from errors or mistakes, or when Terraform specifically suggests to use it as
│ part of an error message.
╵
╷
│ Error: Error updating SystemDhcpServer resource: Internal Server Error - Internal error when processing therequest (500)
│ Cli response: 
│ [Can not set duplicate entry. object check operator error, -15, discard the setting Command fail. Return code -15]
│ 
│   with fortios_systemdhcp_server.vlan80_dhcp,
│   on 04-dhcp-server.tf line 139, in resource "fortios_systemdhcp_server" "vlan80_dhcp":
│  139: resource "fortios_systemdhcp_server" "vlan80_dhcp" {
```

Please let me know if I can provide any more details

**Comment by MaxxLiu22** [comment]
Hi @waza-ari ,

May I know your FortiGate model and firmware version? Also, are you using the latest Terraform FortiOS provider version 1.24.1?

**Comment by waza-ari** [comment]
Hi @MaxxLiu22,

thanks for coming back! It's a Fortigate 70G, 7.4.12 (build 2902). 

FortiOS provider version is indeed 1.24.1

```
$ terraform providers

Providers required by configuration:
.
├── provider[registry.terraform.io/fortinetdev/fortios] 1.24.1
├── provider[registry.terraform.io/hashicorp/random]
└── provider[registry.terraform.io/hashicorp/local]
```

**Comment by waza-ari** [comment]
@MaxxLiu22 anything I can help you with to re-open this issue? We're still seeing the behavior.

**Comment by MaxxLiu22** [comment]
Hi @waza-ari ,

I was able to reproduce the same issue on my side.

Based on the plan log you shared, the element order in your Terraform configuration is `45678123`, while the order returned by the FortiGate is `12345678`. This causes Terraform to detect a mismatch during the comparison.

I suspect that the `id` field is not defined in your `reserved_address` blocks. In that case, FortiGate automatically generates the IDs in ascending order, while the order in your local Terraform configuration is different.

To resolve this, you can either:

* Reorder the `reserved_address` blocks in your Terraform configuration to match the ascending order used by FortiGate, or
* Manually specify the `id` field to prevent FortiGate from auto-generating it, for example:

```hcl
dynamic "reserved_address" {
  for_each = var.dhcp_reservations
  content {
    id          = reserved_address.value.id   # <---------------------
    mac         = reserved_address.value.mac
    ip          = reserved_address.value.ip
    description = reserved_address.value.description
  }
}
```

If the issue still persists after trying the above, please feel free to open a new case so we can investigate it further. It would also be very helpful if you could share your Terraform configuration and any relevant logs.

**Comment by waza-ari** [comment]
Thanks @MaxxLiu22, the id missing was indeed the issue.

In case anyone is wondering about how to fix that in a dynamic yet deterministic way, I'm now generating a unique ID based on the last two octets of the IP address I'm creating a reservation for:

clients:

```json
{
    "VLAN_20": [
        {
            "ip": "10.1.20.20",
            "mac": "d8:3a:dd:aa:ff:ee",
            "description": "client1"
        },
        {
            "ip": "10.1.20.70",
            "mac": "3c:61:05:aa:be:ef",
            "description": "client2"
        }
   ]
}
```

Parsing

```terraform
locals {
  # DHCP reserved addresses (MAC reservations per VLAN interface key)
  dhcp_reserved_clients_raw = jsondecode(file("${path.module}/data/dhcp_reserved_clients.json"))

  # Key each reservation by a stable id derived from the host part of its IP
  # (third octet * 256 + fourth octet, unique down to a /16). The map
  # comprehension also fails the plan on duplicate IPs within a VLAN.
  dhcp_reserved_clients_by_id = {
    for vlan, clients in local.dhcp_reserved_clients_raw :
    vlan => {
      for c in clients :
      format("%05d", tonumber(split(".", c.ip)[2]) * 256 + tonumber(split(".", c.ip)[3])) => c
    }
  }

  # Emit lists sorted by id with the id merged in, so config order always
  # matches FortiGate id-ascending readback order.
  dhcp_reserved_clients = {
    for vlan, by_id in local.dhcp_reserved_clients_by_id :
    vlan => [
      for k in sort(keys(by_id)) :
      merge(by_id[k], { id = tonumber(k) })
    ]
```
